### ISSUE TITLE
Crash when using shaders, still happening.

### ISSUE THREAD

**Issue by TheJessaChannel** [supermassimo/DynamicTeesPlus#11] opened 2022-03-01 11:39 UTC
I see that this is not yet been fixed, here is the report again, in hopes that it gets fixed if the bug is reported enough.
[crash-2022-03-01_03.14.25-client.txt](https://github.com/DynamicTreesTeam/DynamicTreesPlus/files/8161237/crash-2022-03-01_03.14.25-client.txt)

**Comment by Harleyoc1** [comment] 2022-03-01 17:57
Spamming the same bug reports will not make us fix them any faster. 
Duplicate of #8

**Closed as completed by Harleyoc1** 2022-03-01 17:57 UTC

**Comment by Harleyoc1** [comment] 2022-03-01 17:59
The real problem with this bug in particular is OptiFine is closed source which makes it very difficult to diagnose and debug.
